import './Home.css';
import { BrowserRouter as Router, Route, Link } from "react-router-dom";
import Navigation from '../Navigation';
import AboutUs from './AboutUs';
import Registration from './Registration';

function Home () {

    return (

       <div className = "App">

       <img src = {process.env.PUBLIC_URL + "/logo.png"} alt = "" className = "App-logo"/>
       
       <Navigation/>

       <header className = "App-header"> <p> #RUN FOR WATER <br></br> 2022 ｜ 5K </p> </header>

       <div>

         <p>

           Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Augue mauris augue neque gravida. In dictum non consectetur a erat nam at lectus. Eget dolor morbi non arcu risus quis varius quam quisque. Vitae justo eget magna fermentum iaculis eu non. Diam quis enim lobortis scelerisque fermentum dui faucibus in ornare. Sed viverra tellus in hac habitasse platea. Vulputate sapien nec sagittis aliquam malesuada bibendum arcu vitae. Turpis nunc eget lorem dolor sed. Sapien pellentesque habitant morbi tristique senectus et netus et. Ornare arcu dui vivamus arcu felis bibendum ut tristique. Eu facilisis sed odio morbi quis commodo odio aenean sed. Nisl suscipit adipiscing bibendum est ultricies integer quis auctor elit. Fermentum dui faucibus in ornare quam. Nec feugiat in fermentum posuere urna nec tincidunt praesent semper.
           Integer malesuada nunc vel risus commodo viverra maecenas. Semper risus in hendrerit gravida rutrum quisque non tellus. Convallis a cras semper auctor neque vitae tempus. Consequat semper viverra nam libero justo laoreet. Augue ut lectus arcu bibendum. Malesuada nunc vel risus commodo viverra maecenas accumsan lacus vel. Scelerisque varius morbi enim nunc. Blandit turpis cursus in hac habitasse platea dictumst. Arcu dui vivamus arcu felis bibendum ut. Venenatis urna cursus eget nunc scelerisque. Quam adipiscing vitae proin sagittis nisl rhoncus mattis. Est pellentesque elit ullamcorper dignissim cras tincidunt lobortis. Id leo in vitae turpis. Tempus egestas sed sed risus pretium quam vulputate. Nullam vehicula ipsum a arcu cursus vitae congue mauris. Congue nisi vitae suscipit tellus mauris. Viverra nam libero justo laoreet sit amet cursus sit. Libero nunc consequat interdum varius sit amet mattis vulputate enim.
           Elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Ac placerat vestibulum lectus mauris ultrices. Neque volutpat ac tincidunt vitae semper quis lectus. Sed elementum tempus egestas sed sed risus pretium quam. Risus feugiat in ante metus dictum at tempor. Amet mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Accumsan tortor posuere ac ut consequat semper. Odio eu feugiat pretium nibh ipsum consequat nisl. Egestas sed sed risus pretium. Vel elit scelerisque mauris pellentesque pulvinar pellentesque. Vulputate mi sit amet mauris commodo quis imperdiet. Nulla pharetra diam sit amet nisl suscipit. Fermentum et sollicitudin ac orci phasellus egestas. Risus nec feugiat in fermentum posuere. Amet nisl purus in mollis nunc sed id. Viverra accumsan in nisl nisi scelerisque. Pharetra sit amet aliquam id diam maecenas ultricies mi eget. Non pulvinar neque laoreet suspendisse.
           Aliquam sem fringilla ut morbi tincidunt augue. Pulvinar mattis nunc sed blandit libero volutpat sed. Nec sagittis aliquam malesuada bibendum arcu vitae elementum. Eu augue ut lectus arcu. Nunc lobortis mattis aliquam faucibus purus in massa. Cursus vitae congue mauris rhoncus. Cursus vitae congue mauris rhoncus aenean vel elit. Sit amet risus nullam eget felis. Blandit cursus risus at ultrices mi tempus imperdiet nulla. Purus sit amet volutpat consequat mauris. Feugiat nisl pretium fusce id velit. Lectus sit amet est placerat in egestas erat imperdiet. Amet tellus cras adipiscing enim eu. Mattis pellentesque id nibh tortor id. Magna sit amet purus gravida quis blandit turpis. Sit amet facilisis magna etiam tempor orci eu lobortis. Sollicitudin ac orci phasellus egestas tellus. Enim ut sem viverra aliquet eget sit amet tellus. Amet consectetur adipiscing elit pellentesque habitant morbi tristique.
           Tellus elementum sagittis vitae et leo duis. Potenti nullam ac tortor vitae purus faucibus. Ultricies mi quis hendrerit dolor magna eget est lorem ipsum. At tellus at urna condimentum. Duis ut diam quam nulla porttitor massa id neque aliquam. Nibh mauris cursus mattis molestie. Diam volutpat commodo sed egestas egestas fringilla phasellus. Venenatis urna cursus eget nunc scelerisque viverra mauris in. Ut morbi tincidunt augue interdum velit euismod in pellentesque massa. Sed vulputate odio ut enim. Id donec ultrices tincidunt arcu non sodales neque sodales ut. Ornare aenean euismod elementum nisi quis eleifend quam. Tristique risus nec feugiat in fermentum posuere.
           Lacus viverra vitae congue eu consequat. Fermentum et sollicitudin ac orci phasellus. In fermentum posuere urna nec tincidunt praesent semper. Risus sed vulputate odio ut enim blandit volutpat. Sed blandit libero volutpat sed cras. Commodo ullamcorper a lacus vestibulum sed. Purus gravida quis blandit turpis cursus in hac habitasse. Rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt. Massa sed elementum tempus egestas sed sed. Facilisis sed odio morbi quis. Urna porttitor rhoncus dolor purus non enim praesent elementum facilisis. Eu volutpat odio facilisis mauris sit amet massa vitae. Lectus sit amet est placerat in egestas erat imperdiet sed. Felis imperdiet proin fermentum leo vel orci porta non pulvinar. Diam donec adipiscing tristique risus nec feugiat in fermentum posuere. Felis donec et odio pellentesque diam volutpat commodo sed egestas.
           Vitae tortor condimentum lacinia quis vel eros donec ac. Aliquam ut porttitor leo a diam sollicitudin tempor id eu. Nunc consequat interdum varius sit. Metus aliquam eleifend mi in nulla. Orci ac auctor augue mauris augue. Enim praesent elementum facilisis leo vel. Id aliquet lectus proin nibh nisl condimentum id venenatis a. Porttitor rhoncus dolor purus non enim praesent elementum facilisis. Ut tristique et egestas quis ipsum suspendisse ultrices gravida. Cras tincidunt lobortis feugiat vivamus at augue. Etiam tempor orci eu lobortis.
           Orci dapibus ultrices in iaculis nunc sed augue lacus viverra. Amet volutpat consequat mauris nunc congue nisi vitae suscipit. A lacus vestibulum sed arcu non odio euismod. Diam volutpat commodo sed egestas egestas fringilla phasellus faucibus. In cursus turpis massa tincidunt dui ut ornare lectus sit. Dictum non consectetur a erat nam at. Volutpat maecenas volutpat blandit aliquam etiam. Odio pellentesque diam volutpat commodo sed egestas. Id diam vel quam elementum pulvinar etiam non quam lacus. Blandit libero volutpat sed cras. At lectus urna duis convallis convallis tellus id. Sapien nec sagittis aliquam malesuada. Eget arcu dictum varius duis at consectetur lorem. Lorem ipsum dolor sit amet consectetur. Diam volutpat commodo sed egestas egestas fringilla phasellus.
           Neque aliquam vestibulum morbi blandit cursus risus. Aliquet porttitor lacus luctus accumsan tortor posuere. Ultricies lacus sed turpis tincidunt. A lacus vestibulum sed arcu non odio euismod lacinia. Sit amet commodo nulla facilisi nullam. Placerat orci nulla pellentesque dignissim enim sit amet venenatis. Diam maecenas ultricies mi eget mauris pharetra et ultrices. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. In nisl nisi scelerisque eu ultrices vitae auctor. Maecenas accumsan lacus vel facilisis. Fringilla est ullamcorper eget nulla facilisi etiam. Sed euismod nisi porta lorem mollis aliquam. Augue mauris augue neque gravida in fermentum et sollicitudin. Eget dolor morbi non arcu risus quis varius quam quisque. A condimentum vitae sapien pellentesque habitant morbi tristique senectus. Elementum curabitur vitae nunc sed velit dignissim. Accumsan tortor posuere ac ut consequat. Justo eget magna fermentum iaculis eu.
           Mi bibendum neque egestas congue quisque egestas diam in. Ipsum nunc aliquet bibendum enim facilisis. Odio euismod lacinia at quis risus sed. Turpis egestas integer eget aliquet nibh praesent tristique. Aenean et tortor at risus viverra adipiscing. Augue neque gravida in fermentum et sollicitudin. In nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque. Et sollicitudin ac orci phasellus egestas tellus rutrum. Non odio euismod lacinia at quis risus sed. Elit sed vulputate mi sit amet mauris. Lobortis feugiat vivamus at augue eget. Arcu risus quis varius quam quisque id diam. In hac habitasse platea dictumst quisque. Aliquam eleifend mi in nulla posuere sollicitudin. Augue lacus viverra vitae congue eu consequat ac felis. Euismod quis viverra nibh cras pulvinar mattis nunc sed. In dictum non consectetur a erat nam at lectus. Accumsan lacus vel facilisis volutpat est. Blandit massa enim nec dui nunc mattis enim ut.

         </p>
        
       </div>

     </div>

    );

}

export default Home;